version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: iocl-tms-postgres
    environment:
      POSTGRES_DB: iocl_tms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iocl-tms-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: iocl-tms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - iocl-tms-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iocl-tms-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/iocl_tms
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - postgres
      - redis
    networks:
      - iocl-tms-network
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
  redis_data:

networks:
  iocl-tms-network:
    driver: bridge
